// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.ProjectContext;

public partial class Post_PostTag
{
    /// <summary>
    /// 語錄標籤關聯UUID
    /// </summary>
    [Key]
    public Guid PPT_UUID { get; set; }

    /// <summary>
    /// 語錄UUID
    /// </summary>
    public Guid P_UUID { get; set; }

    /// <summary>
    /// 語錄標籤UUID
    /// </summary>
    public Guid PT_UUID { get; set; }

    /// <summary>
    /// 排序
    /// </summary>
    public int PPT_Sort { get; set; }

    /// <summary>
    /// 創建人
    /// </summary>
    [StringLength(50)]
    public string Creator { get; set; }

    /// <summary>
    /// 創建時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? CreateTime { get; set; }

    /// <summary>
    /// 更新人
    /// </summary>
    [StringLength(50)]
    public string Updator { get; set; }

    /// <summary>
    /// 更新時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? UpdateTime { get; set; }

    [ForeignKey("PT_UUID")]
    [InverseProperty("Post_PostTag")]
    public virtual Post_Tag PT_UU { get; set; }

    [ForeignKey("P_UUID")]
    [InverseProperty("Post_PostTag")]
    public virtual Post_Post P_UU { get; set; }
}