// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.ProjectContext;

/// <summary>
/// 負能量語錄主表
/// </summary>
public partial class Post_Post
{
    /// <summary>
    /// 識別編碼
    /// </summary>
    [Key]
    public Guid P_UUID { get; set; }

    /// <summary>
    /// 負能量語錄
    /// </summary>
    [Required]
    public string P_Post { get; set; }

    /// <summary>
    /// 排序
    /// </summary>
    public int U_Sort { get; set; }

    /// <summary>
    /// 創建人
    /// </summary>
    [StringLength(50)]
    public string Creator { get; set; }

    /// <summary>
    /// 創建時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? CreateTime { get; set; }

    /// <summary>
    /// 更新人
    /// </summary>
    [StringLength(50)]
    public string Updator { get; set; }

    /// <summary>
    /// 更新時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? UpdateTime { get; set; }

    [InverseProperty("P_UU")]
    public virtual ICollection<Post_PostTag> Post_PostTag { get; set; } = new List<Post_PostTag>();

    [InverseProperty("P_UU")]
    public virtual ICollection<User_UserPost> User_UserPost { get; set; } = new List<User_UserPost>();
}