// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.ProjectContext;

public partial class Post_Tag
{
    [Key]
    public Guid PT_UUID { get; set; }

    [Required]
    [StringLength(50)]
    public string PT_Tag { get; set; }

    /// <summary>
    /// 排序
    /// </summary>
    public int PT_Sort { get; set; }

    /// <summary>
    /// 創建人
    /// </summary>
    [StringLength(50)]
    public string Creator { get; set; }

    /// <summary>
    /// 創建時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? CreateTime { get; set; }

    /// <summary>
    /// 更新人
    /// </summary>
    [StringLength(50)]
    public string Updator { get; set; }

    /// <summary>
    /// 更新時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? UpdateTime { get; set; }

    [InverseProperty("PT_UU")]
    public virtual ICollection<Post_PostTag> Post_PostTag { get; set; } = new List<Post_PostTag>();
}