// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.ProjectContext;

public partial class ProjectContext : DbContext
{
    public ProjectContext(DbContextOptions<ProjectContext> options)
        : base(options)
    {
    }

    public virtual DbSet<User_UserAccount> User_UserAccount { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<User_UserAccount>(entity =>
        {
            entity.Property(e => e.U_UUID)
                .ValueGeneratedNever()
                .HasComment("UUID");
            entity.Property(e => e.CreateTime).HasComment("創建時間");
            entity.Property(e => e.Creator).HasComment("創建人");
            entity.Property(e => e.U_Account).HasComment("帳號");
            entity.Property(e => e.U_EMail).HasComment("電子信箱");
            entity.Property(e => e.U_Name).HasComment("姓名");
            entity.Property(e => e.U_Pwd).HasComment("密碼");
            entity.Property(e => e.U_Sort)
                .ValueGeneratedOnAdd()
                .HasComment("排序");
            entity.Property(e => e.U_Tel).HasComment("電話");
            entity.Property(e => e.UpdateTime).HasComment("更新時間");
            entity.Property(e => e.Updator).HasComment("更新人");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}